sudo: false
language: node_js
node_js:
  - "7"
  - "6"

services:
  - docker

before_install:
  - docker pull mongo
  - docker run -d -p 27071:27017 mongo

script:
  - npm test

after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
